# Generated by Django 2.1.7 on 2019-03-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='dinner',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='lunch',
            field=models.SmallIntegerField(default=0),
        ),
    ]
